using Newtonsoft.Json;

namespace Rofl.Reader.Models
{
    public class Player
    {
        [JsonProperty("DatabaseId")]
        public string Id { get; set; }

        public string NAME { get; set; }

        [JsonProperty("ID")]
        public string PlayerID { get; set; }
        public string SKIN { get; set; }
        public string TEAM { get; set; }
        public string WIN { get; set; }
        public string EXP { get; set; }
        public string LEVEL { get; set; }
        public string GOLD_SPENT { get; set; }
        public string GOLD_EARNED { get; set; }
        public string MINIONS_KILLED { get; set; }
        public string NEUTRAL_MINIONS_KILLED { get; set; }
        public string NEUTRAL_MINIONS_KILLED_YOUR_JUNGLE { get; set; }
        public string NEUTRAL_MINIONS_KILLED_ENEMY_JUNGLE { get; set; }
        public string CHAMPIONS_KILLED { get; set; }
        public string NUM_DEATHS { get; set; }
        public string ASSISTS { get; set; }
        public string LARGEST_KILLING_SPREE { get; set; }
        public string KILLING_SPREES { get; set; }
        public string LARGEST_MULTI_KILL { get; set; }
        public string BOUNTY_LEVEL { get; set; }
        public string DOUBLE_KILLS { get; set; }
        public string TRIPLE_KILLS { get; set; }
        public string QUADRA_KILLS { get; set; }
        public string PENTA_KILLS { get; set; }
        public string UNREAL_KILLS { get; set; }
        public string BARRACKS_KILLED { get; set; }
        public string TURRETS_KILLED { get; set; }
        public string HQ_KILLED { get; set; }
        public string OBJECTIVES_STOLEN { get; set; }
        public string OBJECTIVES_STOLEN_ASSISTS { get; set; }
        public string FRIENDLY_DAMPEN_LOST { get; set; }
        public string FRIENDLY_TURRET_LOST { get; set; }
        public string FRIENDLY_HQ_LOST { get; set; }
        public string BARON_KILLS { get; set; }
        public string DRAGON_KILLS { get; set; }
        public string NODE_CAPTURE { get; set; }
        public string NODE_CAPTURE_ASSIST { get; set; }
        public string NODE_NEUTRALIZE { get; set; }
        public string NODE_NEUTRALIZE_ASSIST { get; set; }
        public string TEAM_OBJECTIVE { get; set; }
        public string PLAYER_SCORE_0 { get; set; }
        public string PLAYER_SCORE_1 { get; set; }
        public string PLAYER_SCORE_2 { get; set; }
        public string PLAYER_SCORE_3 { get; set; }
        public string PLAYER_SCORE_4 { get; set; }
        public string PLAYER_SCORE_5 { get; set; }
        public string PLAYER_SCORE_6 { get; set; }
        public string PLAYER_SCORE_7 { get; set; }
        public string PLAYER_SCORE_8 { get; set; }
        public string PLAYER_SCORE_9 { get; set; }
        public string PLAYER_SCORE_10 { get; set; }
        public string PLAYER_SCORE_11 { get; set; }
        public string VICTORY_POINT_TOTAL { get; set; }
        public string TOTAL_PLAYER_SCORE { get; set; }
        public string COMBAT_PLAYER_SCORE { get; set; }
        public string OBJECTIVE_PLAYER_SCORE { get; set; }
        public string TOTAL_SCORE_RANK { get; set; }
        public string ITEMS_PURCHASED { get; set; }
        public string CONSUMABLES_PURCHASED { get; set; }
        public string ITEM0 { get; set; }
        public string ITEM1 { get; set; }
        public string ITEM2 { get; set; }
        public string ITEM3 { get; set; }
        public string ITEM4 { get; set; }
        public string ITEM5 { get; set; }
        public string ITEM6 { get; set; }
        public string PERK0 { get; set; }
        public string PERK0_VAR1 { get; set; }
        public string PERK0_VAR2 { get; set; }
        public string PERK0_VAR3 { get; set; }
        public string PERK1 { get; set; }
        public string PERK1_VAR1 { get; set; }
        public string PERK1_VAR2 { get; set; }
        public string PERK1_VAR3 { get; set; }
        public string PERK2 { get; set; }
        public string PERK2_VAR1 { get; set; }
        public string PERK2_VAR2 { get; set; }
        public string PERK2_VAR3 { get; set; }
        public string PERK3 { get; set; }
        public string PERK3_VAR1 { get; set; }
        public string PERK3_VAR2 { get; set; }
        public string PERK3_VAR3 { get; set; }
        public string PERK4 { get; set; }
        public string PERK4_VAR1 { get; set; }
        public string PERK4_VAR2 { get; set; }
        public string PERK4_VAR3 { get; set; }
        public string PERK5 { get; set; }
        public string PERK5_VAR1 { get; set; }
        public string PERK5_VAR2 { get; set; }
        public string PERK5_VAR3 { get; set; }
        public string PERK_PRIMARY_STYLE { get; set; }
        public string PERK_SUB_STYLE { get; set; }
        public string STAT_PERK_0 { get; set; }
        public string STAT_PERK_1 { get; set; }
        public string STAT_PERK_2 { get; set; }
        public string SIGHT_WARDS_BOUGHT_IN_GAME { get; set; }
        public string VISION_WARDS_BOUGHT_IN_GAME { get; set; }
        public string WARD_PLACED { get; set; }
        public string WARD_KILLED { get; set; }
        public string WARD_PLACED_DETECTOR { get; set; }
        public string VISION_SCORE { get; set; }
        public string SPELL1_CAST { get; set; }
        public string SPELL2_CAST { get; set; }
        public string SPELL3_CAST { get; set; }
        public string SPELL4_CAST { get; set; }
        public string SUMMON_SPELL1_CAST { get; set; }
        public string SUMMON_SPELL2_CAST { get; set; }
        public string KEYSTONE_ID { get; set; }
        public string TOTAL_DAMAGE_DEALT { get; set; }
        public string PHYSICAL_DAMAGE_DEALT_PLAYER { get; set; }
        public string MAGIC_DAMAGE_DEALT_PLAYER { get; set; }
        public string TRUE_DAMAGE_DEALT_PLAYER { get; set; }
        public string TOTAL_DAMAGE_DEALT_TO_CHAMPIONS { get; set; }
        public string PHYSICAL_DAMAGE_DEALT_TO_CHAMPIONS { get; set; }
        public string MAGIC_DAMAGE_DEALT_TO_CHAMPIONS { get; set; }
        public string TRUE_DAMAGE_DEALT_TO_CHAMPIONS { get; set; }
        public string TOTAL_DAMAGE_TAKEN { get; set; }
        public string PHYSICAL_DAMAGE_TAKEN { get; set; }
        public string MAGIC_DAMAGE_TAKEN { get; set; }
        public string TRUE_DAMAGE_TAKEN { get; set; }
        public string TOTAL_DAMAGE_SELF_MITIGATED { get; set; }
        public string TOTAL_DAMAGE_SHIELDED_ON_TEAMMATES { get; set; }
        public string TOTAL_DAMAGE_DEALT_TO_BUILDINGS { get; set; }
        public string TOTAL_DAMAGE_DEALT_TO_TURRETS { get; set; }
        public string TOTAL_DAMAGE_DEALT_TO_OBJECTIVES { get; set; }
        public string LARGEST_CRITICAL_STRIKE { get; set; }
        public string TOTAL_TIME_CROWD_CONTROL_DEALT { get; set; }
        public string TOTAL_HEAL { get; set; }
        public string TOTAL_HEAL_ON_TEAMMATES { get; set; }
        public string TOTAL_UNITS_HEALED { get; set; }
        public string TIME_PLAYED { get; set; }
        public string LONGEST_TIME_SPENT_LIVING { get; set; }
        public string TOTAL_TIME_SPENT_DEAD { get; set; }
        public string TIME_OF_FROM_LAST_DISCONNECT { get; set; }
        public string TIME_SPENT_DISCONNECTED { get; set; }
        public string TIME_CCING_OTHERS { get; set; }
        public string WAS_AFK { get; set; }
        public string WAS_AFK_AFTER_FAILED_SURRENDER { get; set; }
        public string WAS_EARLY_SURRENDER_ACCOMPLICE { get; set; }
        public string TEAM_EARLY_SURRENDERED { get; set; }
        public string GAME_ENDED_IN_EARLY_SURRENDER { get; set; }
        public string GAME_ENDED_IN_SURRENDER { get; set; }
        public string PLAYERS_I_MUTED { get; set; }
        public string PLAYERS_THAT_MUTED_ME { get; set; }
        public string MUTED_ALL { get; set; }
        public string PING { get; set; }
        public string PLAYER_ROLE { get; set; }
        public string PLAYER_POSITION { get; set; }
        public string CHAMPION_TRANSFORM { get; set; }
        public string TEAM_POSITION { get; set; }
        public string INDIVIDUAL_POSITION { get; set; }
        public string CHAMPION_MISSION_STAT_0 { get; set; }
        public string CHAMPION_MISSION_STAT_1 { get; set; }
        public string CHAMPION_MISSION_STAT_2 { get; set; }
        public string CHAMPION_MISSION_STAT_3 { get; set; }
    }
}
