name: Build

on:
  push:
    branches: 
      - master
    paths: 'src/**'

jobs:
  build:
    runs-on: [windows-latest]
    steps:
    - name: Checkout files
      uses: actions/checkout@v1
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Publish ReplayBook
      run: |
        dotnet publish -p:PublishProfile=FolderProfile

        # remove debugging files
        Remove-Item ./publish/*.pdb
        Remove-Item ./publish/sni.dll
      shell: pwsh

    - name: Run runes packaging script
      run: python ./src/scripts/generate-runes.py
    
    - name: Copy runes to release
      run: |
        Copy-Item -Path "./runes" -Destination "./publish/data" -Recurse
      shell: pwsh

    - name: Package release
      run: |
        Compress-Archive ./publish ./ReplayBook.zip
      shell: pwsh

    - name: Create Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ReplayBook-Test
        path: ./ReplayBook.zip