name: Build

on: workflow_call

jobs:
  build:
    runs-on: [windows-latest]
    steps:
    - name: Checkout files
      uses: actions/checkout@v1
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Run ReplayBook publish profile
      run: |
        dotnet publish -p:PublishProfile=FolderProfile -p:Configuration=Release -p:DebugSymbols=false -p:DebugType=None
      shell: pwsh

    - name: Package release
      run: |
        Compress-Archive ./publish/* ./ReplayBook.zip
      shell: pwsh

    - name: Create Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ReplayBook-Build
        path: ./ReplayBook.zip