name: Build

on:
  push:
    branches: 
      - master
    paths: 'src/**'

jobs:
  build:
    runs-on: [windows-latest]
    steps:
    - name: Checkout files
      uses: actions/checkout@v1
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Add msbuild.exe to PATH
      uses: microsoft/setup-msbuild@v1.1
      
    # - name: Add nuget.exe to PATH
    #   uses: nuget/setup-nuget@v1
      
    # - name: Restore NuGet packages
    #   run: nuget restore ReplayBook.sln

    - name: Restore NuGet packages
      run: msbuild -t:restore
      
    - name: Build solution
      run: msbuild ReplayBook.sln -p:Configuration="Release" -p:Platform="Any CPU"

    - name: Run runes packaging script
      run: python ./scripts/generate-runes.py
    
    - name: Copy runes to release
      run: |
        Copy-Item -Path "./runes" -Destination "./src/Rofl.UI.Main/bin/Release/lib" -Recurse
      shell: pwsh

    - name: Package release
      run: |
        Compress-Archive ./src/Rofl.UI.Main/bin/Release ./ReplayBook.zip
      shell: pwsh

    - name: Create Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ReplayBook-Test
        path: ./ReplayBook.zip